---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: SOURCE
comment: false
coverage:
  status:
    project:
      default:
        threshold: 10%
    patch:
      default:
        threshold: 20%
fixes:
  - "/tmp/ANDR-RECOV-*/root/tmp/*-customize.sh::zip-content/customize.sh"
  - "/tmp/ANDR-RECOV-*/root/tmp/custom-setup-a5k/default-settings.conf::zip-content/settings.conf"
