---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: SOURCE
coverage:
  status:
    project:
      default:
        threshold: 10%
    patch:
      default:
        threshold: 20%
fixes:
  - "/tmp/ANDR-RECOV-*/root/tmp/custom-setup-a5k/::/home/runner/work/microg-unofficial-installer-test/microg-unofficial-installer-test/"
comment: false
codecov:
  disable_default_path_fixes: true
